pipeline {
    agent any

    environment {
        ORACLE_PWD = credentials('ORACLE_PWD')
        ANSIBLE_PASS = credentials('ANSIBLE_PASS')
    }

    stages {
        stage('Pull image') {
            steps {
                echo 'Updating docker image'
                sh 'sudo docker pull aruko/firstdockerfile:latest'
            }
        }
        
        stage('Run container') {
            steps {
                sh 'sudo rm -r -f *'
                sh 'ls'
                sh 'echo \"ORACLE_PWD=$ORACLE_PWD\" > .env'
                sh 'echo \"$ANSIBLE_PASS\" > ansible-vault.txt'
                sh 'curl https://raw.githubusercontent.com/Better-than-Elon/my-mle-template/main/CD/docker-compose.yml -o docker-compose.yml'
                sh 'ls'
                sh 'sudo docker compose up web'
            }
        }
    }
    post {
        always {
            sh 'sudo docker compose down 2>null'
            sh 'sudo docker logout docker.io'
        }
    }
}
