pipeline {
    agent any

    stages {
        stage('Pull image') {
            steps {
                echo 'Updating docker image'
                sh 'sudo docker pull aruko/firstdockerfile:latest'
            }
        }
        
        stage('Run container') {
            steps {
//                 sh 'curl https://raw.githubusercontent.com/Better-than-Elon/my-mle-template/main/CD/docker-compose.yml -o docker-compose.yml'
                sh 'cd CD'
                sh 'sudo docker compose up'
            }
        }
    }
    post {
        always {
            sh 'sudo docker compose down 2>null'
            sh 'sudo docker logout docker.io'
        }
    }
}
